# Generated by Django 4.1.4 on 2022-12-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_lastview_view_method_visit_view_delete_lastvisit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='session',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='view',
        ),
        migrations.AlterField(
            model_name='accountimage',
            name='image',
            field=models.ImageField(upload_to='Media/Account/images/'),
        ),
        migrations.DeleteModel(
            name='LastView',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
