# Generated by Django 4.1.4 on 2023-01-10 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0004_rename_accountimage_profileimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileImage',
            new_name='Profile',
        ),
    ]
