# Generated by Django 4.1.4 on 2023-01-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='long_name_en',
            field=models.CharField(default='', max_length=32),
        ),
    ]
