# Generated by Django 4.1.4 on 2022-12-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_alter_image_image_alter_video_actors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.RemoveField(
            model_name='mainimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
        migrations.RemoveField(
            model_name='video',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='video',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='coutries',
        ),
        migrations.RemoveField(
            model_name='video',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='video',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='producers',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='BgImage',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='MainImage',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
