# Generated by Django 4.1.4 on 2022-12-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_language_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
