# Generated by Django 4.1.4 on 2022-12-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_page_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='style',
            field=models.TextField(default=''),
        ),
    ]
