# Generated by Django 4.1.4 on 2022-12-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_page_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='style',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.language')),
                ('maintext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.maintext')),
            ],
        ),
    ]
