# Generated by Django 4.1.3 on 2022-12-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_maintext_alter_page_style_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('email', models.CharField(max_length=128)),
                ('readed', models.BooleanField(default=False)),
                ('detetime', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
