# Generated by Django 4.1.4 on 2022-12-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_message_delete_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='detetime',
            new_name='datetime',
        ),
    ]
