# Generated by Django 4.1.4 on 2022-12-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_rename_detetime_message_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
