# Generated by Django 4.1.4 on 2023-01-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='language',
        ),
        migrations.RemoveField(
            model_name='text',
            name='maintext',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='MainText',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
