# Generated by Django 4.1.4 on 2023-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
